# dein.vim
[[plugins]]
repo = 'Shougo/dein.vim'

# vim-devicons
[[plugins]]
repo = 'ryanoasis/vim-devicons'

# NERDTree
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
    nnoremap <silent><C-n> :NERDTreeToggle<CR>  " Ctrl-nでファイルツリーの表示切り替え
    let g:NERDTreeShowBookmarks=1               " ブックマークを初期表示
    let g:webdevicons_enable_nerdtree=1         " vim-deviconsを使用
    if !argc()
        autocmd vimenter * NERDTree|normal gg3j " ファイル指定で開かれた場合はNERDTreeは表示しない
    endif
'''

# カラーテーマにicebergを設定
[[plugins]]
repo = 'cocopon/iceberg.vim'
